LayoutAndViews/Models/ListModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LayoutAndViews.Models
{
    public class ListModel
    {
        public static List<Person> ListOfPeople = new List<Person>();
    }
}

LayoutAndViews/Models/NumberCheck.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LayoutAndViews.Models
{
    public static class NumberCheck
    {
        public static string CheckNumber(double input)
        {
            string result = "";

            if (input > 10)
            {
                result = "Number is larger than 10";
            }
            else if (input == 10)
            {
                result = "Number is exactly 10";
            }
            else
                result = "Number is smaller than 10";

            return result;
        }
    }
}

LayoutAndViews/Models/Person.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LayoutAndViews.Models
{
    public class Person
    {
        public string Name { get; set; }
        public string Address { get; set; }
        public int Age { get; set; }
    }
}

LayoutAndViews/Controllers/HomeController.cs
using LayoutAndViews.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LayoutAndViews.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            ListModel.ListOfPeople.Add(new Person { Name = "Krall", Age = 30, Address = "Storgatan 23" });
            ListModel.ListOfPeople.Add(new Person { Name = "Jonathan", Age = 33, Address = "Gatan 5" });
            ListModel.ListOfPeople.Add(new Person { Name = "Linus", Age = 44, Address = "Vägen 7" });

            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult CheckNumber()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CheckNumber(double input)
        {
            ViewBag.Result = NumberCheck.CheckNumber(input);

            return View();
        }
    }
}

LayoutAndViews/Controllers/PeopleController.cs
using LayoutAndViews.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LayoutAndViews.Controllers
{
    public class PeopleController : Controller
    {
        // GET: People
        public ActionResult Index()
        {

            return View(ListModel.ListOfPeople);
        }

       
        public ActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult Create(string name, string address, int age)
        {
            ListModel.ListOfPeople.Add(new Person { Name = name, Address = address, Age = age });

            return RedirectToAction("Index");
        }
    }
}

LayoutAndViews/Views/Home/About.cshtml
@{
    
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>About</title>
</head>
<body>
    <div> 
        About Mikaels första MVC!
    </div>
</body>
</html>

LayoutAndViews/Views/Home/CheckNumber.cshtml
@{
    ViewBag.Title = "CheckNumber";
}

<h2>Check if number is 10</h2>

@using (Html.BeginForm("CheckNumber", "Home", FormMethod.Post))
{
    <input type="number" name="input" value="0" />
    <input type="submit" class="btn-primary" value="Check" />
}

@if (ViewBag.Result != null)
{
    @ViewBag.Result
}

LayoutAndViews/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

LayoutAndViews/Views/People/Create.cshtml
@model LayoutAndViews.Models.Person

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Person</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

LayoutAndViews/Views/People/Index.cshtml
@model IEnumerable<LayoutAndViews.Models.Person>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Age)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        @Html.Partial("_PersonPartial", item)
    </tr>
}

</table>

LayoutAndViews/Views/People/_PersonPartial.cshtml
@model LayoutAndViews.Models.Person

<td>
    @Model.Name
</td>
<td>
    @Model.Address
</td>
<td>
    @Model.Age
</td>

LayoutAndViews/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <img src="~/Content/Images/Csharp_Logo.png" class="pull-left" alt="C# logo" width="48px" height="48px" />
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Layout and views", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("List of people", "Index", "People")</li>
                    <li>@Html.ActionLink("Check number", "CheckNumber", "Home")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mikaels första ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>